# Generated by Django 4.2.30 on 2026-05-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Furniture', 'Furniture'), ('Paintings', 'Paintings'), ('Sculptures', 'Sculptures'), ('Photos', 'Photos')], max_length=50)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='artworks/')),
                ('painting_medium', models.CharField(blank=True, choices=[('Oil', 'Oil'), ('Water', 'Water'), ('Acrylic', 'Acrylic'), ('Other', 'Other')], max_length=50, null=True)),
                ('sculpture_material', models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Marble', 'Marble'), ('Wood', 'Wood'), ('Clay', 'Clay'), ('Other', 'Other')], max_length=50, null=True)),
                ('furniture_material', models.CharField(blank=True, choices=[('Wood', 'Wood'), ('Metal', 'Metal'), ('Glass', 'Glass'), ('Other', 'Other')], max_length=50, null=True)),
                ('photo_technique', models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Film', 'Film'), ('Black & White', 'Black & White'), ('Other', 'Other')], max_length=50, null=True)),
                ('painting_style', models.CharField(blank=True, choices=[('Impressionism', 'Impressionism'), ('Modernism', 'Modernism'), ('Surrealism', 'Surrealism'), ('Realism', 'Realism'), ('Other', 'Other')], max_length=50, null=True)),
                ('sculpture_style', models.CharField(blank=True, choices=[('Abstract', 'Abstract'), ('Figurative', 'Figurative'), ('Minimalist', 'Minimalist'), ('Contemporary', 'Contemporary'), ('Other', 'Other')], max_length=50, null=True)),
                ('furniture_style', models.CharField(blank=True, choices=[('Victorian', 'Victorian'), ('Art Deco', 'Art Deco'), ('Modern', 'Modern'), ('Minimalist', 'Minimalist'), ('Other', 'Other')], max_length=50, null=True)),
                ('photo_style', models.CharField(blank=True, choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape'), ('Street', 'Street'), ('Abstract', 'Abstract'), ('Other', 'Other')], max_length=50, null=True)),
                ('edition', models.CharField(choices=[('Original', 'Original'), ('Limited Edition', 'Limited Edition'), ('Open Edition', 'Open Edition'), ('Other', 'Other')], max_length=50)),
                ('provenance', models.TextField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork')),
            ],
        ),
    ]
