# Generated by Django 4.2.30 on 2026-05-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='style',
        ),
        migrations.AddField(
            model_name='artwork',
            name='furniture_material',
            field=models.CharField(blank=True, choices=[('Wood', 'Wood'), ('Metal', 'Metal'), ('Glass', 'Glass'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='furniture_style',
            field=models.CharField(blank=True, choices=[('Victorian', 'Victorian'), ('Art Deco', 'Art Deco'), ('Modern', 'Modern'), ('Minimalist', 'Minimalist'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='jewellery_material',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='jewellery_style',
            field=models.CharField(blank=True, choices=[('Classic', 'Classic'), ('Modern', 'Modern'), ('Vintage', 'Vintage'), ('Handmade', 'Handmade'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='painting_medium',
            field=models.CharField(blank=True, choices=[('Oil', 'Oil'), ('Water', 'Water'), ('Acrylic', 'Acrylic'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='painting_style',
            field=models.CharField(blank=True, choices=[('Impressionism', 'Impressionism'), ('Modernism', 'Modernism'), ('Surrealism', 'Surrealism'), ('Realism', 'Realism'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='photo_style',
            field=models.CharField(blank=True, choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape'), ('Street', 'Street'), ('Abstract', 'Abstract'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='photo_technique',
            field=models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Film', 'Film'), ('Black & White', 'Black & White'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sculpture_material',
            field=models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Marble', 'Marble'), ('Wood', 'Wood'), ('Clay', 'Clay'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sculpture_style',
            field=models.CharField(blank=True, choices=[('Abstract', 'Abstract'), ('Figurative', 'Figurative'), ('Minimalist', 'Minimalist'), ('Contemporary', 'Contemporary'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='edition',
            field=models.CharField(choices=[('Original', 'Original'), ('Limited Edition', 'Limited Edition'), ('Open Edition', 'Open Edition'), ('Other', 'Other')], max_length=50),
        ),
    ]
