# Generated by Django 6.0.4 on 2026-05-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_seller_update_artwork_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='height_cm',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='created_at',
            new_name='listing_date',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='starting_bid_price',
            new_name='starting_bid',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='width_cm',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='year_created',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='material',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='technique_or_medium',
        ),
        migrations.AddField(
            model_name='artwork',
            name='furniture_material',
            field=models.CharField(blank=True, choices=[('Wood', 'Wood'), ('Metal', 'Metal'), ('Glass', 'Glass'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='painting_medium',
            field=models.CharField(blank=True, choices=[('Oil', 'Oil'), ('Water', 'Water'), ('Acrylic', 'Acrylic'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='photo_technique',
            field=models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Film', 'Film'), ('Black & White', 'Black & White'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sculpture_material',
            field=models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Marble', 'Marble'), ('Wood', 'Wood'), ('Clay', 'Clay'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Paintings', 'Paintings'), ('Sculptures', 'Sculptures'), ('Photos', 'Photos'), ('Jewellery', 'Jewellery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artworks.seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='style',
            field=models.CharField(blank=True, choices=[('Modern', 'Modern'), ('Classic', 'Classic'), ('Abstract', 'Abstract'), ('Realism', 'Realism'), ('Minimalist', 'Minimalist'), ('Vintage', 'Vintage'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork')),
            ],
        ),
    ]
