# Generated by Django 6.0.4 on 2026-05-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artwork_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='length',
            new_name='depth',
        ),
    ]
