# Generated by Django 4.2.30 on 2026-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artwork_id_alter_artworkimage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='jewellery_material',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='jewellery_style',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Paintings', 'Paintings'), ('Sculptures', 'Sculptures'), ('Photos', 'Photos')], max_length=50),
        ),
    ]
