# Generated by Django 6.0.4 on 2026-05-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('artworks', '0003_rename_height_cm_artwork_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='accounts.seller'),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
