# Generated by Django 6.0.4 on 2026-05-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_rename_length_artwork_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='painting_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='photo_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sculpture_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
