# Generated by Django 6.0.4 on 2026-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_alter_artwork_painting_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='furniture_material',
            field=models.CharField(blank=True, choices=[('Textile', 'Textile'), ('Wood', 'Wood'), ('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Leather', 'Leather'), ('Artificial leather', 'Artificial leather'), ('Glass', 'Glass'), ('Steel', 'Steel'), ('Concrete', 'Concrete'), ('Marble', 'Marble'), ('Bronze', 'Bronze'), ('Stone', 'Stone'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='furniture_style',
            field=models.CharField(blank=True, choices=[('Contemporary', 'Contemporary'), ('Art Deco', 'Art Deco'), ('Minimalism', 'Minimalism'), ('Renaissance', 'Renaissance'), ('Modernism', 'Modernism'), ('Baroque', 'Baroque'), ('Maximalism', 'Maximalism'), ('Classicism', 'Classicism'), ('Post modernism', 'Post modernism'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='painting_medium',
            field=models.CharField(blank=True, choices=[('Oil painting', 'Oil painting'), ('Watercolor painting', 'Watercolor painting'), ('Acrylic painting', 'Acrylic painting'), ('Gouache', 'Gouache'), ('Encaustic', 'Encaustic'), ('Tempera', 'Tempera'), ('Fresco', 'Fresco'), ('Ink', 'Ink'), ('Charcoal', 'Charcoal'), ('Chalk', 'Chalk'), ('Graphite', 'Graphite'), ('Spray Painting', 'Spray Painting'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='photo_technique',
            field=models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Film', 'Film'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
