# Generated by Django 6.0.4 on 2026-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_alter_artwork_furniture_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='painting_style',
            field=models.CharField(blank=True, choices=[('Renaissance (14th - 17th century)', 'Renaissance (14th - 17th century)'), ('Baroque (17th - mid 18th century)', 'Baroque (17th - mid 18th century)'), ('Rococo (Early 18th century)', 'Rococo (Early 18th century)'), ('Neoclassicism (18th - 19th century)', 'Neoclassicism (18th - 19th century)'), ('Romanticism (1750 - 1890)', 'Romanticism (1750 - 1890)'), ('Realism (1830 - )', 'Realism (1830 - )'), ('Impressionism (1870 - 1880s)', 'Impressionism (1870 - 1880s)'), ('Post-Impressionism (1886 - 1905)', 'Post-Impressionism (1886 - 1905)'), ('Expressionism (1905 - 1920s)', 'Expressionism (1905 - 1920s)'), ('Fauvism (1905 - 1908)', 'Fauvism (1905 - 1908)'), ('Cubism (1907 - 1914)', 'Cubism (1907 - 1914)'), ('Surrealism (1920s - )', 'Surrealism (1920s - )'), ('Abstract Art (1910s - )', 'Abstract Art (1910s - )'), ('Futurism (1909 - 1914)', 'Futurism (1909 - 1914)'), ('Pop Art (1950s - 1960s)', 'Pop Art (1950s - 1960s)'), ('Minimalism (1960s - 1970s)', 'Minimalism (1960s - 1970s)'), ('Photorealism (1960s - 1970s)', 'Photorealism (1960s - 1970s)'), ('Contemporary art (1970s - now)', 'Contemporary art (1970s - now)'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='photo_style',
            field=models.CharField(blank=True, choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait'), ('Fashion', 'Fashion'), ('Black and white', 'Black and white'), ('Astrophotography', 'Astrophotography'), ('Aerial', 'Aerial'), ('Editorial', 'Editorial'), ('Food', 'Food'), ('Architectural', 'Architectural'), ('Headshot', 'Headshot'), ('Nature', 'Nature'), ('Sports', 'Sports'), ('Conceptual', 'Conceptual'), ('Abstract', 'Abstract'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sculpture_style',
            field=models.CharField(blank=True, choices=[('Abstract', 'Abstract'), ('Land', 'Land'), ('Relief', 'Relief'), ('Freestanding', 'Freestanding'), ('Carved', 'Carved'), ('Modeling', 'Modeling'), ('Assembled', 'Assembled'), ('Cast', 'Cast'), ('Minimalism', 'Minimalism'), ('Constructivism', 'Constructivism'), ('Surrealism', 'Surrealism'), ('Kinetic Art', 'Kinetic Art'), ('Contemporary', 'Contemporary'), ('Figurative Art', 'Figurative Art'), ('Modern art', 'Modern art'), ('Modernism', 'Modernism'), ('Cubism', 'Cubism'), ('Baroque', 'Baroque'), ('Renaissance', 'Renaissance'), ('Expressionism', 'Expressionism'), ('Classicism', 'Classicism'), ('Hyperrealism', 'Hyperrealism'), ('Concrete art', 'Concrete art'), ('Futurism', 'Futurism'), ('Gothic art', 'Gothic art'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
