# Generated by Django 6.0.4 on 2026-05-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_alter_artwork_height_alter_artwork_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='painting_style',
            field=models.CharField(blank=True, choices=[('Renaissance (14th - 17th century)', 'Renaissance (14th - 17th century)'), ('Baroque (17th - mid 18th century)', 'Baroque (17th - mid 18th century)'), ('Rococo (Early 18th century)', 'Rococo (Early 18th century)'), ('Neoclassicism (18th - 19th century)', 'Neoclassicism (18th - 19th century)'), ('Romanticism (1750 - 1890)', 'Romanticism (1750 - 1890)'), ('Realism (1830 - )', 'Realism (1830 - )'), ('Impressionism (1870 - 1880s)', 'Impressionism (1870 - 1880s)'), ('Post-Impressionism (1886 - 1905)', 'Post-Impressionism (1886 - 1905)'), ('Expressionism (1905 - 1920s)', 'Expressionism (1905 - 1920s)'), ('Fauvism (1905 - 1908)', 'Fauvism (1905 - 1908)'), ('Cubism (1907 - 1914)', 'Cubism (1907 - 1914)'), ('Surrealism (1920s - )', 'Surrealism (1920s - )'), ('Abstract Art (1910s - )', 'Abstract Art (1910s - )'), ('Futurism (1909 - 1914)', 'Futurism (1909 - 1914)'), ('Pop Art (1950s - 1960s)', 'Pop Art (1950s - 1960s)'), ('Minimalism (1960s - 1970s)', 'Minimalism (1960s - 1970s)'), ('Photorealism (1960s - 1970s)', 'Photorealism (1960s - 1970s)'), ('Contemporary art (1970s - now)', 'Contemporary art (1970s - now)'), ('Modernism', 'Modernism'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
