# Generated by Django 6.0.4 on 2026-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_alter_artwork_painting_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='painting_style',
            field=models.CharField(blank=True, choices=[('Renaissance', 'Renaissance'), ('Baroque', 'Baroque'), ('Rococo', 'Rococo'), ('Neoclassicism', 'Neoclassicism'), ('Romanticism', 'Romanticism'), ('Realism', 'Realism'), ('Impressionism', 'Impressionism'), ('Post-Impressionism', 'Post-Impressionism'), ('Expressionism', 'Expressionism'), ('Fauvism', 'Fauvism'), ('Cubism', 'Cubism'), ('Surrealism', 'Surrealism'), ('Abstract Art', 'Abstract Art'), ('Futurism', 'Futurism'), ('Pop Art', 'Pop Art'), ('Minimalism', 'Minimalism'), ('Photorealism', 'Photorealism'), ('Contemporary art', 'Contemporary art'), ('Modernism', 'Modernism'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
