# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='seller_cancel_notification_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Contingent', 'Contingent'), ('Finalized', 'Finalized'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
