# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bid_seller_cancel_notification_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='buyer_accept_notification_seen',
            field=models.BooleanField(default=False),
        ),
    ]
