# Generated by Django 6.0.4 on 2026-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_bid_buyer_accept_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='buyer_reject_notification_seen',
            field=models.BooleanField(default=False),
        ),
    ]
